### ISSUE TITLE
Deprecate SHA-1 cv passes

### ISSUE THREAD

**Issue by AntiFreeze** [ValiMail/arc_test_suite#10]
The consensus of the DMARC work group (https://www.ietf.org/mail-archive/web/dmarc/current/msg04040.html) is that SHA-1 tests should fail the test suite now that DCRUP has deprecated SHA-1.

Due to this, two tests should be switched from cv=pass to cv=fail:
- ams_fields_a_sha1
- as_fields_a_sha1

**Comment by kitterma** [comment]
This is now enshrined in RFC 8301.

**Comment by kitterma** [comment]
Fixed in commit 97c1fe6.
